---
fixtures:
  repositories:
    apache: 'https://github.com/puppetlabs/puppetlabs-apache'
    candlepin:     "https://github.com/theforeman/puppet-candlepin.git"
    certs: 'https://github.com/theforeman/puppet-certs'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    extlib: 'https://github.com/voxpupuli/puppet-extlib'
    foreman: 'https://github.com/theforeman/puppet-foreman'
    katello:       "https://github.com/theforeman/puppet-katello.git"
    hashfile: "https://github.com/southalc/hashfile"
    redis:         "https://github.com/voxpupuli/puppet-redis"
    podman:
      repo: 'https://github.com/ehelms/puppet-podman'
      branch: 'fix-secret'
    postgresql: 'https://github.com/puppetlabs/puppetlabs-postgresql'
    selinux_core: 'https://github.com/puppetlabs/puppetlabs-selinux_core'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    systemd: 'https://github.com/voxpupuli/puppet-systemd'
